### ISSUE TITLE
Change tutorial.md to README.md

### ISSUE THREAD

**Issue by cowang4** [burtonwilliamt/carlogicapi#11]
If we do this and change the links on the wiki then the README will show when you are browsing that folder on GitHub, like [this](https://github.com/burtonwilliamt/carlogicapi/tree/master/tutorials/VeinsTutorial).

**Comment by burtonwilliamt** [comment]
Changed. Also, the links in the sidebar now go to the root of each tutorial, not the README.md or the location in the tutorial wiki page. Because the docs are now named README.md they will show up along with the files, like you demonstrated above.

**Comment by cowang4** [comment]
Perfect!
