### ISSUE TITLE
Need help with diagrams

### ISSUE THREAD

**Issue by burtonwilliamt** [burtonwilliamt/carlogicapi#13]
Hey guys. Hoping you had some ideas for the diagrams. I did a pass at them, and I think they're improving but I'd like to color them so that it's easy to see what carries over from the implementation to the architecture documents. Also I need some proofreading of implementation and I need to document architecture.

**Comment by burtonwilliamt** [comment]
Just did the architecture descriptions, so if you guys could look over that and proof read/suggest any improvements that would be good.

**Comment by cowang4** [comment]
I think we fixed these in preparation for our presentation.
