### ISSUE TITLE
Some errors after build

### ISSUE THREAD

**Issue by maans88** [burtonwilliamt/carlogicapi#17]
I am thinking I am using a different version of Veins than you guys are using, can you tell me what version you are using or if there's an updated code?

Thank you.

src/TutorialAppl.cpp:18:23: error: ‘class Veins::TraCICommandInterface::Vehicle’ has no member named ‘setLaneChangeMode’
         traciVehicle->setLaneChangeMode(0);
                       ^
src/TutorialAppl.cpp: In member function ‘virtual void TutorialAppl::sendWSM(WaveShortMessage*)’:
src/TutorialAppl.cpp:51:26: error: ‘individualOffset’ was not declared in this scope
     sendDelayedDown(wsm, individualOffset);
                          ^
src/TutorialAppl.cpp: In member function ‘void TutorialAppl::sendMessage(std::__cxx11::string)’:
src/TutorialAppl.cpp:56:91: error: ‘prepareWSM’ was not declared in this scope
     WaveShortMessage* wsm = prepareWSM("data", dataLengthBits, channel, dataPriority, -1,2);
                                                                                           ^
make: *** [out/gcc-debug//src/TutorialAppl.o] Error 1
Makefile:102: recipe for target 'out/gcc-debug//src/TutorialAppl.o' faile

**Comment by Greg-Gravyty** [comment]
Yeah, we used our own forked version with extra function calls.
https://github.com/burtonwilliamt/veins

**Comment by maans88** [comment]
Thank you. What version of SUMO did you guys use?

**Comment by cowang4** [comment]
The latest one at the time. It shouldn't matter much.
Greg

On Saturday, August 12, 2017, 9:21:46 AM EDT, Maan Joseph <notifications@github.com> wrote:


Thank you. What version of SUMO did you guys use?

**Comment by maans88** [comment]
What version of OMNET did you guys use? I am new to this setup, can you pin point the application files you guys wrote? I'd like to run your simulation if that's possible.

**Comment by cowang4** [comment]
We wrote installation guides on the project's wiki:
https://github.com/burtonwilliamt/carlogicapi/wiki

**Comment by maans88** [comment]
Do you remember what version you used for OMNET? I don't think it would run on 5.1. was it version 5?

**Comment by cowang4** [comment]
It looks like we used Omnet Version 4.6
