### ISSUE TITLE
Need help. Thanks.

### ISSUE THREAD

**Issue by JiaGuoWMU** [burtonwilliamt/carlogicapi#18]
I imported the VeinTutorial as well as the Vein, but got the following error while building the project. Any help is appreciated.

02:25:37 **** Build of configuration gcc-debug for project VeinsTutorial ****
make MODE=debug all 
src/TutorialAppl.cpp
In file included from src/TutorialAppl.cpp:3:0:
src/TutorialAppl.h:11:68: fatal error: veins/modules/application/ieee80211p/BaseWaveApplLayer.h: No such file or directory
compilation terminated.
Makefile:108: recipe for target 'out/gcc-debug//src/TutorialAppl.o' failed
make: *** [out/gcc-debug//src/TutorialAppl.o] Error 1

02:25:38 Build Finished (took 431ms)

**Comment by cowang4** [comment]
Try to recompile the veins library first. See https://github.com/burtonwilliamt/carlogicapi/tree/master/tutorials/VeinsTutorial#troubleshooting
