### ISSUE TITLE
Write a Veins example walkthrough

### ISSUE THREAD

**Issue by cowang4** [burtonwilliamt/carlogicapi#2]
There is no documentation for the Veins example! Noooo. We'll have to do this the hard way and write our own.

**Comment by cowang4** [comment]
Alright @burtonwilliamt It is ready for you to try. Please provide feedback.

**Comment by burtonwilliamt** [comment]
First note: a bit confused on how to open a .ned file as source/text

**Comment by burtonwilliamt** [comment]
Second note: the slowDown() TraCI function actually can also speed up a car if the new speed is higher than the current. Might be helpful to explain that the cars aren't always slowing down, rather matching the speed sent to them.

**Comment by burtonwilliamt** [comment]
I'm referring to the line where you say "I've made the cars slow down when they receive a message from another car. " I know that you talk later about how they are actually matching each other, but I got a little confused at first.

**Comment by burtonwilliamt** [comment]
The omnetpp.ini explanation at the top of the code is a little confusing. For example, what are these variables used for? What imports them?

**Comment by burtonwilliamt** [comment]
Also, where is the omnetpp.ini that we are supposed to run at the very bottom of the readme? Presumably this is the VeinsTutorial/simulations/omnetpp.ini

**Comment by burtonwilliamt** [comment]
When I tried to run the code, I got: 

```
Exception occurred executing command line.
Cannot run program "/Users/localadmin/Documents/RCOS/carlogicapi/tutorials/VeinsTutorial/VeinsTutorial" (in directory "/Users/localadmin/Documents/RCOS/carlogicapi/tutorials/VeinsTutorial/simulations"): error=2, No such file or directory
```

**Comment by cowang4** [comment]
Okay. I've addressed all the concerns noted here and updated the tutorial.
