### ISSUE TITLE
fatal error: veins/modules/application/ieee80211p/BaseWaveApplLayer.h: No such file or directory

### ISSUE THREAD

**Issue by micleb** [burtonwilliamt/carlogicapi#20]
Hi, I need to use your veins tutorial but I can't build the project
Here is the output error : 
```
15:02:35 **** Incremental Build of configuration gcc-debug for project VeinsTutorial ****
make MODE=debug all 
src/TutorialAppl.cpp
In file included from src/TutorialAppl.cpp:3:0:
src/TutorialAppl.h:11:68: fatal error: veins/modules/application/ieee80211p/BaseWaveApplLayer.h: No such file or directory
 #include "veins/modules/application/ieee80211p/BaseWaveApplLayer.h"
                                                                    ^
compilation terminated.
Makefile:101: recipe for target 'out/gcc-debug//src/TutorialAppl.o' failed
make: *** [out/gcc-debug//src/TutorialAppl.o] Error 1

15:02:36 Build Finished (took 166ms)
```
When I do : `right click on VeinsTutorial project > properties > Project references`, veins is checked

Veins, OMNET and Sumo are all working, I can launch the erlangen demo.

Here are the version I own :
OMNET++ version 5.1.1
VEINS version 4.6
SUMO 0.30

Could you help me ?

Thank you

**Comment by abdelaha** [comment]
I have the same issue. For some reason, the builder does not see the veins package under [veins root directory]/src/veins. However, I can access these files from the Omnet++ IDE by right-click -> open deceleration. 

In this tutorial, what do you mean by ". Do the same but Import Veins from its source location. ". You can only import Venis from its root location.

**Comment by micleb** [comment]
I fixed those errors in the PR #21.

Like I said in the pull request, we need to use the [burtonwilliamt veins' fork](https://github.com/burtonwilliamt/veins)

**Comment by cowang4** [comment]
Thanks for explaining how to compile. I'm glad that you got it to work.

Yes, you will need to use our Veins fork because of some functions that we added.

**Comment by cowang4** [comment]
Cool,

I added your problem and solution to the VeinsTutorial Readme in the Troubleshooting section.
[New section](https://github.com/burtonwilliamt/carlogicapi/blob/master/tutorials/VeinsTutorial/README.md#no-such-file-basewaveapplayerh)

So, now I'm going to close this issue.

**Comment by abdelaha** [comment]
@micleb 
 burtonwilliamt veins' fork  doesn't compile with me successfully. 
I got this error:
veins/base/modules/BaseMacLayer.cc:74:67: error: cast from 'const char*' to 'LAddress::L2Type {aka long int}' loses precision [-fpermissive]
                 myMacAddr = LAddress::L2Type(addressString.c_str());

any idea!

**Comment by micleb** [comment]
Well, I didn't use the burtonwilliamt veins' fork completely.

I used the original, but I added this function to `veins/src/veins/modules/mobility/traci/TraCICommandInterface.cc` from the burtonwilliamt veins' fork : https://github.com/burtonwilliamt/veins/blob/e754c2554677cec0cbfc1ebb08215580454be55d/src/veins/modules/mobility/traci/TraCICommandInterface.cc#L61-L66

And the signature's function to `veins/src/veins/modules/mobility/traci/TraCICommandInterface.h`: https://github.com/burtonwilliamt/veins/blob/e754c2554677cec0cbfc1ebb08215580454be55d/src/veins/modules/mobility/traci/TraCICommandInterface.h#L43

Then rebuild veins with the new function added, then rebuild veinstutorial and it should worked

@cowang4 Thank you, glad to help !

**Comment by ruisonghan** [comment]
> Well, I didn't use the burtonwilliamt veins' fork completely.
> 
> I used the original, but I added this function to `veins/src/veins/modules/mobility/traci/TraCICommandInterface.cc` from the burtonwilliamt veins' fork : https://github.com/burtonwilliamt/veins/blob/e754c2554677cec0cbfc1ebb08215580454be55d/src/veins/modules/mobility/traci/TraCICommandInterface.cc#L61-L66
> 
> And the signature's function to `veins/src/veins/modules/mobility/traci/TraCICommandInterface.h`: https://github.com/burtonwilliamt/veins/blob/e754c2554677cec0cbfc1ebb08215580454be55d/src/veins/modules/mobility/traci/TraCICommandInterface.h#L43
> 
> Then rebuild veins with the new function added, then rebuild veinstutorial and it should worked
> 
> @cowang4 Thank you, glad to help !

Following this solution, we can solve this problem.

**Comment by ynuwm** [comment]
> Well, I didn't use the burtonwilliamt veins' fork completely.
> 
> I used the original, but I added this function to `veins/src/veins/modules/mobility/traci/TraCICommandInterface.cc` from the burtonwilliamt veins' fork : https://github.com/burtonwilliamt/veins/blob/e754c2554677cec0cbfc1ebb08215580454be55d/src/veins/modules/mobility/traci/TraCICommandInterface.cc#L61-L66
> 
> And the signature's function to `veins/src/veins/modules/mobility/traci/TraCICommandInterface.h`: https://github.com/burtonwilliamt/veins/blob/e754c2554677cec0cbfc1ebb08215580454be55d/src/veins/modules/mobility/traci/TraCICommandInterface.h#L43
> 
> Then rebuild veins with the new function added, then rebuild veinstutorial and it should worked
> 
> @cowang4 Thank you, glad to help !

which version of veins do you use
