### ISSUE TITLE
Setup Alpha simulation

### ISSUE THREAD

**Issue by cowang4** [burtonwilliamt/carlogicapi#5]
I don't think the alpha folder will work currently. We probably need a OMNet++ IDE project that imports / includes from veins and such.

**Comment by burtonwilliamt** [comment]
Even if you were to duplicate the veins-veins-4.4/examples/veins/ folder where it is? I am not able to test this as my current installation of omnet++ crashes even when I run the default veins test. I was able to run the sumo simulation though, so that't good!

**Comment by burtonwilliamt** [comment]
As far as sumo is concerned alpha has everything necessary, so it must be either an omnet++ dependency, or a veins dependency. My guess is the later, put potentially the former.

**Comment by cowang4** [comment]
What I mean is that we should commit an OMNet++ project. Which has the imports for Veins and everything already included so that someone can clone and then just File > Import our project to work on it. We'll need another folder for the SUMO code probably.

**Comment by burtonwilliamt** [comment]
What do we need to do to create an importable OMNet++ project?

**Comment by cowang4** [comment]
- Create OMNet++ project: File->new->OMNeT project->Empty project
- Veins must be imported into the workspace in order to use it: Import-> Existing projects into workspace-> Veins if it isn't already there
- Add Veins to Project->Properties->Project References

**Comment by burtonwilliamt** [comment]
Alpha omnet project has been created, we are now developing the alpha setup.
