### ISSUE TITLE
Setup Sumo autonomous driving tutorial

### ISSUE THREAD

**Issue by burtonwilliamt** [burtonwilliamt/carlogicapi#8]

**Comment by burtonwilliamt** [comment]
Made this, but it's more of a TraCI tutorial. It is a modification of the hello sumo tutorial. I have the one car driving along, then when it gets above 5m/s speed, it slows down in the next three seconds, then accelerates again. Very rudimentary, but a self driving car nonetheless. It still needs documentation, but that's a different issue.

**Comment by cowang4** [comment]
Quite literally another issue #10. But cool! That wasn't too hard! Good work!

**Comment by burtonwilliamt** [comment]
Haha intentional, I'm using Milestones now. Not sure how useful it is, but it's fun!
