### ISSUE TITLE
Design page

### ISSUE THREAD

**Issue by burtonwilliamt** [burtonwilliamt/carlogicapi#9]
Do we need a design page? Right now I'm not really sure how it is going to fit into the documentation, or how to populate it. Maybe we can make a diagram of inheritance or the structure of the code?

**Comment by cowang4** [comment]
Yeah I was thinking something like a diagram.

**Comment by cowang4** [comment]
I have some ideas. What if we have a simplified version of [this](http://veins.car2x.org/documentation/veins-arch.png) that shows just OMNet++, Veins, TraCI, and SUMO. Then a description of how our prototype fits in.

**Comment by burtonwilliamt** [comment]
Yeah, that's what I was thinking. We can also link our tutorial of each component.

**Comment by cowang4** [comment]
The Home page of the Wiki also has Design related stuff. We need to figure out where that will go. I'm thinking Design goes on the Home page since Home related stuff is in the project's README.

**Comment by burtonwilliamt** [comment]
Yeah. I think that sounds pretty good. That way, once you see all of the components, you can decide what you want to focus on.

**Comment by burtonwilliamt** [comment]
The design page is essentially what the diagrams are, so this discussion should continue there.
